### ISSUE TITLE
现在的加载时间比之前慢多了

### ISSUE THREAD

**Issue by Ynwaspectre** [zhongshaofa/easyadmin#108]
好像ckeditor每次都要加载 1.6秒

**Comment by zhongshaofa** [comment]
演示环境？

**Comment by Ynwaspectre** [comment]
@zhongshaofa app_debug 和 IS_DEMO都是false  为什么js后面的version不会变成2.0 还是时间戳

**Comment by zhongshaofa** [comment]
> @zhongshaofa app_debug 和 IS_DEMO都是false 为什么js后面的version不会变成2.0 还是时间戳

哪一个版本？

**Comment by Ynwaspectre** [comment]
@zhongshaofa 就最新的 刚拉去

**Comment by zhongshaofa** [comment]
> @zhongshaofa 就最新的 刚拉去

我晚上看看

**Comment by Ynwaspectre** [comment]
@zhongshaofa 3q

**Comment by Ynwaspectre** [comment]
@zhongshaofa 兄弟不用看了 我的env的问题
