### ISSUE TITLE
静态文件一下子全部加载，太大了加载超时

### ISSUE THREAD

**Issue by gantoday** [zhongshaofa/easyadmin#25]
![image](https://user-images.githubusercontent.com/7780154/88514330-77746580-d01c-11ea-8ac0-0d900c5634d8.png)

打开后台首页直接就加载4.2MB静态资源。太大了，廉价服务器顶不住啊。
经常统计图js 或者 富文本js 下载失败。下载失败页面就打不开了，卡在转圈圈。
请问这里能优化一下吗。
刚进后台首页没必要这么早下载富文本js。
建议优化下。

**Comment by zhongshaofa** [comment]
那就将静态资源放到OSS上，我的演示站点的静态资源也都是放在OSS上的

**Comment by gantoday** [comment]
![image](https://user-images.githubusercontent.com/7780154/88515225-f027f180-d01d-11ea-9937-4b4d25d10f31.png)
我是加了阿里云cdn了。还是zhe这样。
谢谢你的建议，我换到oss试一试。
不过还是建议首页不要拉那么多静态资源。

**Comment by gantoday** [comment]
好像静态资源js会自动加时间戳，导致cdn失效。

**Comment by zhongshaofa** [comment]
> 好像静态资源js会自动加时间戳，导致cdn失效。

有版本管理的，把debug关了就不会有这种情况了

**Comment by gantoday** [comment]
关闭debug。cdn生效。可以了。
![image](https://user-images.githubusercontent.com/7780154/88515574-7e03dc80-d01e-11ea-99ff-b62283fee0ac.png)
但是这两个请求，请问怎么去掉呢
`https://api.github.com/repos/zhongshaofa/easyadmin?callback=callback`
项目里搜索，搜不到

**Comment by zhongshaofa** [comment]
> 关闭debug。cdn生效。可以了。
> ![image](https://user-images.githubusercontent.com/7780154/88515574-7e03dc80-d01e-11ea-99ff-b62283fee0ac.png)
> 但是这两个请求，请问怎么去掉呢
> `https://api.github.com/repos/zhongshaofa/easyadmin?callback=callback`
> 项目里搜索，搜不到

**Comment by zhongshaofa** [comment]
> > 关闭debug。cdn生效。可以了。
> > ![image](https://user-images.githubusercontent.com/7780154/88515574-7e03dc80-d01e-11ea-99ff-b62283fee0ac.png)
> > 但是这两个请求，请问怎么去掉呢
> > `https://api.github.com/repos/zhongshaofa/easyadmin?callback=callback`
> > 项目里搜索，搜不到

首页欢迎页

**Comment by gantoday** [comment]
谢谢
