### ISSUE TITLE
easy-admin.js 不支持 lay-verify="required|phone|number" 

### ISSUE THREAD

**Issue by mingdh** [zhongshaofa/easyadmin#42]
easy-admin.js 不支持 lay-verify="required|phone|number", 特别是需要自定义验证时，required|xxxx 形式时，required无法出现 * 号。以下代码相应修改为：
formRequired: function () {
...

                   //     if (verify === 'required') {  修改为：
                  if (verify.toLowerCase().indexOf('required') !== -1) {

**Comment by zhongshaofa** [comment]
新版已支持
