### ISSUE TITLE
vendor目录是否需要上传

### ISSUE THREAD

**Issue by ayuayue** [zhongshaofa/easyadmin#76]
在本地开发时没发现项目是有 vendor 目录的,当把项目放到 linux 上并取消上传 vendor 目录后,使用 composer 进行安装依赖.
pathinfo nginx 配置没有问题,总是无法识别多应用.最后发现vendor目录是原项目自带的,使用 composer 生成的 service.php  中没有注册 think/app/service.
一般 vendor 目录不是不建议上传吗,不建议改动源码或库,而且上传拉取项目,如果依赖很多速度会很慢

**Comment by cshaptx4869** [comment]
可以把 vendor/zhongshaofa/easy-admin/src 目录移动到 tp 的 extend 目录下并改名为 EasyAdmin 然后再取消 git 的 vendor 上传
