### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [zhongshaofa/easyadmin#77]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by am0o0** [comment]
Hey easyadmin team, can you just give me any feedback please?

**Comment by zhongshaofa** [comment]
Hello, my email is 2286732552@qq.com , looking forward to communicating with you, thank you!

**Comment by am0o0** [comment]
Hello my dear
Can I ask you to tell me that did you receive any email? and then Can I ask you give me some feedback my dear?
If you saw the reports and accept the validity of them I want to ask you to validate them on Huntr.dev and they will remain hidden until you submit the fix commits.
Best regards, Amammad.

**Comment by zhongshaofa** [comment]
> Hello my dear
> Can I ask you to tell me that did you receive any email? and then Can I ask you give me some feedback my dear?
> If you saw the reports and accept the validity of them I want to ask you to validate them on Huntr.dev and they will remain hidden until you submit the fix commits.
> Best regards, Amammad.

In fact, it's not a security issue. It's just a simple restriction of the demo site (you can't access it without get requests), because the default user of the demo site is admin, which is convenient for all functions to be displayed; In the version used by actual users, there will be strict permission system control, accurate to method authorization.

**Comment by am0o0** [comment]
In CSRF attacks it is enough to users with some privileges ( admin or users with some access ) open a website !!!
I didn't get what you mean about access ?
Whole application vulnerable to CSRF attacks then In the strict permission system also we can perform CSRF attacks.
If you read this issue I want to ask you remove this message.

**Comment by zhongshaofa** [comment]
> In CSRF attacks it is enough to users with some privileges ( admin or users with some access ) open a website !!!
> I didn't get what you mean about access ?
> Whole application vulnerable to CSRF attacks then In the strict permission system also we can perform CSRF attacks.
> If you read this issue I want to ask you remove this message.

I understand what you mean, I will fix it tonight, thank you

**Comment by amammad** [comment]
Can I ask you to follow Huntr procedure and just validate my reports, they will remain hidden until you submit a patch.
thanks.

**Comment by amammad** [comment]
there is a option when you put you mouse on your profile picture on Huntr.dev named Reports 
![image](https://user-images.githubusercontent.com/77095239/133072513-aa3f1a2c-281f-4f3b-b095-8b07304c9632.png)

you can see all reports related to your repository when you click on it.

**Comment by zhongshaofa** [comment]
这个bug已修复

**Comment by amammad** [comment]
https://huntr.dev/bounties/7e98debf-4342-4844-b8d4-db1d1d9eb972/
https://huntr.dev/bounties/a05dec2a-1962-4a5f-96a4-52e7d41e4870/
https://huntr.dev/bounties/762b03d1-6330-40be-8933-f1d498b32c85/
https://huntr.dev/bounties/c1b5a731-af85-471e-bfd8-ea7d1624a65c/
https://huntr.dev/bounties/b7f5bfad-107f-4d27-800b-e4f26e87c364/
https://huntr.dev/bounties/7e0fa193-466a-4e7e-9543-8f05ff6ada3e/
https://huntr.dev/bounties/51c15a8b-76c0-48c3-aac7-fad2bd3204a3/
Please validate this CSRFs too that are for difference endpoints

**Comment by amammad** [comment]
Why you want to bothering me my dear ?? I help you to secure your application and you don't respect me at all!!
