### ISSUE TITLE
上传管理中删除整页后，刷新不出数据，页码丢失

### ISSUE THREAD

**Issue by 814096703** [zhongshaofa/easyadmin#8]
删除一页后自动刷新，但是没有刷新出东西，而且底部的页码也不见了，只能关掉标签，再重新打开

**Comment by zhongshaofa** [comment]
没有数据时， 底部页码会不显示的。 另外， 删除等操作是会刷新table的

**Comment by 814096703** [comment]
正常来讲，在删除第二页的数据后，该显示第一页的数据，但这里直接显示无数据，甚至页码都不给你看见了
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mr.Chung"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月28日(星期天) 中午1:05
收件人:&nbsp;"zhongshaofa/easyadmin"<easyadmin@noreply.github.com&gt;;
抄送:&nbsp;"qw"<814096703@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zhongshaofa/easyadmin] 上传管理中删除整页后，刷新不出数据，页码丢失 (#8)





 
没有数据时， 底部页码会不显示的。 另外， 删除等操作是会刷新table的
